name: try-phi
version: 0.1.0.0
github: fizruk/try-phi
license: BSD3
author: Nikolai Kudasov
maintainer: nickolay.kudasov@gmail.com
copyright: 2021 Nikolai Kudasov
extra-source-files:
  - README.md
description: Please see the README on GitHub at <https://github.com/fizruk/try-phi#readme>
custom-setup:
  dependencies:
    - base
    - Cabal
    - cabal-doctest >=1.0.2 && <1.1
ghc-options:
  - '-Wall -fno-warn-type-defaults -O2'
dependencies:
  - base >= 4.7 && < 5
  - ansi-terminal
  - bifunctors
  - bound
  - containers
  - deepseq
  - fgl
  - free
  - graphviz
  - hashable
  - insert-ordered-containers
  - kan-extensions
  - logict
  - mtl
  - parsers
  - prettyprinter
  - prettyprinter-ansi-terminal
  - profunctors
  - text
  - transformers
  - trifecta
  - unordered-containers
  - ref-tf
  - eo-parser
  - miso
  - xmonad-contrib
  - directory
library:
  source-dirs: src
executables:
  try-phi:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - '-threaded'
      - '-rtsopts'
      - '-with-rtsopts=-N'
    when:
      - condition: impl(ghcjs)
        then:
          dependencies:
            - try-phi
            - miso >= 1.8
            - jsaddle
        else:
          dependencies:
            - try-phi
            - miso >= 1.8
            - jsaddle
            - jsaddle-warp
            - warp
tests:
  spec:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - '-threaded'
      - '-rtsopts'
      - '-with-rtsopts=-N'
    dependencies:
      - try-phi
      - hspec
      - QuickCheck
  doctests:
    source-dirs: test
    main: doctests.hs
    other-modules: []
    dependencies:
      - base
      - doctest
      - Glob
      - QuickCheck
      - template-haskell
