-- File generated by the BNF Converter (bnfc 2.9.4).

-- | The abstract syntax of language Sum.

module Sum.Abs where

import Prelude (Integer)
import qualified Prelude as C (Eq, Ord, Show, Read)

data Exp = EInt Integer | EPlus Exp Integer
  deriving (C.Eq, C.Ord, C.Show, C.Read)

