-- File generated by the BNF Converter (bnfc 2.9.4).

-- Templates for pattern matching on abstract syntax

{-# OPTIONS_GHC -fno-warn-unused-matches #-}

module Sum.Skel where

import Prelude (($), Either(..), String, (++), Show, show)
import qualified Sum.Abs

type Err = Either String
type Result = Err String

failure :: Show a => a -> Result
failure x = Left $ "Undefined case: " ++ show x

transExp :: Sum.Abs.Exp -> Result
transExp x = case x of
  Sum.Abs.EInt integer -> failure x
  Sum.Abs.EPlus exp integer -> failure x
