name: Prepare Nix

# Syntax
# https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#about-yaml-syntax-for-github-actions

description: Install Nix, log in to cachix, cache flake inputs and shell

inputs:
  ROOT:
    description: a dir for which this action should be run
    required: true
  GITHUB_TOKEN:
    description: GitHub token
    required: true
  CACHE:
    description: cache name
    default: deemp

runs:
  using: composite
  steps:
    - name: Install Nix
      uses: cachix/install-nix-action@v17
      with:
        extra_nix_config: |
          access-tokens = github.com=${{ inputs.GITHUB_TOKEN }}
          substituters = https://deemp.cachix.org https://cache.nixos.org/ https://hydra.iohk.io https://nix-community.cachix.org
          trusted-public-keys = deemp.cachix.org-1:9shDxyR2ANqEPQEEYDL/xIOnoPwxHot21L5fiZnFL18= cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ= nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs=

    # - uses: cachix/cachix-action@v10
    #   with:
    #     name: ${{ env.cache }}
    #     authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
    # - name: Push inputs to cachix
    #   run: |
    #     # https://docs.cachix.org/pushing#flakes

    #     nix flake archive --json \
    #       | jq -r '.path,(.inputs|to_entries[].value.path)' \
    #       | cachix push ${{ matrix.cache }}
    #     # shell: bash
    # - name: Push devshell to cachix
    #   run: |
    #     nix develop --profile dev-profile
    #     cachix push ${{ matrix.cache }} dev-profile
    #   # shell: bash
