-- File generated by the BNF Converter (bnfc 2.9.4).

-- | The abstract syntax of language try-eo.

module TryEo.Abs where

import qualified Prelude as C (Eq, Ord, Show, Read)

data Hash = EHash
  deriving (C.Eq, C.Ord, C.Show, C.Read)

