name: Front CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    defaults:
        run:
          working-directory: front
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node toolchain
        uses: actions/setup-node@v1
        with:
          node-version: "16.x"

      - name: Cache PureScript dependencies
        uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-spago-${{ hashFiles('**/*.dhall') }}
          path: |
            .spago
            output

      - name: Cache NPM dependencies
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install NPM dependencies
        run: npm install

      - name: Build the project
        run: npm run build-gh-pages
      
      - name: GitHub Pages action
        uses: peaceiris/actions-gh-pages@v3.7.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # example with a default working dir and a publish dir
          # https://github.com/peaceiris/actions-gh-pages#%EF%B8%8F-docusaurus
          publish_dir: ./front/docs
          force_orphan: true