on:
  workflow_call:
    inputs:
      ROOT:
        required: true
        type: string
    secrets:
      CACHIX_AUTH_TOKEN:
        required: true

jobs:
  prepare-nix:
    name: Prepare Nix
    runs-on: ${{ matrix.os }}
    env:
      CACHE: br4ch1st0chr0n3-nix-managed
    steps:
      - name: Checkout main
        uses: actions/checkout@v3
      - name: Install Nix
        uses: cachix/install-nix-action@v17
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
            substituters = https://br4ch1st0chr0n3-nix-managed.cachix.org https://br4ch1st0chr0n3-flakes.cachix.org https://cache.nixos.org/ https://hydra.iohk.io https://nix-community.cachix.org
            trusted-public-keys = br4ch1st0chr0n3-nix-managed.cachix.org-1:sDKsfgu5fCCxNwVhZg+AWeGvbLlEtZoyzkSNKRM/KAo= br4ch1st0chr0n3-flakes.cachix.org-1:Dyc2yLlRIkdbq8CtfOe24QQhQVduQaezkyV8J9RhuZ8= cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ= nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs=

      # - uses: cachix/cachix-action@v10
      #   with:
      #     name: ${{ env.cache }}
      #     authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      # - name: Push inputs to cachix
      #   run: |
      #     # https://docs.cachix.org/pushing#flakes

      #     nix flake archive --json \
      #       | jq -r '.path,(.inputs|to_entries[].value.path)' \
      #       | cachix push ${{ matrix.cache }}
      # - name: Push devshell to cachix
      #   run: |
      #     nix develop --profile dev-profile
      #     cachix push ${{ matrix.cache }} dev-profile
